name: Build and Release APK

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  releases:
    name: Build and Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Get version from pubspec.yaml
        id: version
        run: echo "::set-output name=version::$(grep "version:" pubspec.yaml | cut -c10-)"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get packages
        run: flutter pub get

      - name: Generate Java keystore
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
        run: echo "$KEY_JKS" | base64 --decode > release-keystore.jks

      - name: Build APK
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: flutter build apk --split-per-abi

      - name: Rename APK to MovieApp.apk
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/MovieApp.apk

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(TZ='Asia/Jakarta' date +'%A %d-%m-%Y %T WIB')"

      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/app/outputs/flutter-apk/MovieApp.apk"
          body: "Published at ${{ steps.date.outputs.date }}"
          name: "v${{ steps.version.outputs.version }}"
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.version.outputs.version }}
